import React, { createContext, useContext, useState, ReactNode } from 'react';
import { Language } from '../types';

export const translations: Record<Language, Record<string, string>> = {
  English: {
    // General & Header
    appName: "EasyLife",
    tagline: "Don't learn the interface. Let the interface learn you.",
    home: "Home",
    healthcare: "Healthcare",
    services: "Services",
    emergency: "Emergency",
    help: "Help",
    family: "My Trusted People",
    myDay: "My Day",
    scamShield: "Scam Shield",
    accessibility: "Accessibility",
    whyWeBuilt: "Why We Built",
    designPrinciples: "Design Principles",
    accessibilityAudit: "Accessibility Audit",
    
    // Header Actions
    textSize: "Text Size",
    contrast: "Contrast",
    highContrast: "High Contrast",
    standardContrast: "Standard Contrast",
    readAloud: "Read Aloud",
    emergencyHelp: "EMERGENCY HELP",
    imStuck: "I'M STUCK — HELP ME",
    
    // Homepage
    heroTitle: "Technology doesn't have to be difficult.",
    heroSubtitle: "Simple tools for everyday life — designed with you in mind.",
    startHere: "Start Here — Let's Setup",
    readPageAloud: "Read This Page Aloud",
    greeting: "Good morning",
    mainQuestion: "What do you need today?",
    tellEasyLife: "Tell EasyLife what you need",
    voicePlaceholder: "Tap the microphone and speak...",
    
    // Service Cards
    healthcareTitle: "Healthcare",
    healthcareDesc: "Find hospitals, doctors and appointments.",
    moneyTitle: "Money & Banking",
    moneyDesc: "Understand banking, pensions and financial safety.",
    travelTitle: "Travel",
    travelDesc: "Find simple transport and directions.",
    govtTitle: "Government Services",
    govtDesc: "Get help with government services and applications.",
    emergencyTitle: "Emergency",
    emergencyDesc: "Get emergency help quickly.",
    familyTitle: "Contact Family",
    familyDesc: "Call or message someone you trust.",
    
    // Extra Homepage Sections
    whatMakesDifferent: "What makes EasyLife different?",
    diff1: "It can explain complicated information.",
    diff2: "It can guide you step by step.",
    diff3: "It can read important information aloud.",
    diff4: "It can help identify suspicious messages.",
    diff5: "It lets you ask a trusted person for help.",
    
    youAreInControl: "You are in control",
    ctrl1: "Easy to read",
    ctrl2: "Easy to hear",
    ctrl3: "Easy to understand",
    ctrl4: "Available in your language",
    ctrl5: "No technical knowledge required",

    // Signature Features
    explainThis: "Explain This",
    showMe: "Show Me",
    scamShieldTitle: "Is this message safe?",
    confidenceCheckTitle: "You're all done!",
    
    // Onboarding
    onboardingTitle: "Let's make EasyLife comfortable for you.",
    onboardingSub: "You don't need to know how to use technology. We'll guide you.",
    q1: "How would you like information?",
    q2: "How much help would you like?",
    q3: "What text size is comfortable?",
    q4: "Which language do you prefer?",
    savePreferences: "Save My Preferences",
    
    // Common Buttons
    goBack: "Go Back",
    confirm: "Confirm",
    cancel: "Cancel",
    close: "Close",
    yes: "Yes",
    no: "No",
    startAgain: "Start Again",
    call: "Call",
    message: "Message"
  },
  
  Tamil: {
    // General & Header
    appName: "ஈசி லைஃப் (EasyLife)",
    tagline: "தொழில்நுட்பத்தை கற்றுக்கொள்ள வேண்டாம். உங்களுக்கேற்ப இடைமுகம் மாறும்.",
    home: "முகப்பு",
    healthcare: "மருத்துவ சேவை",
    services: "சேவைகள்",
    emergency: "அவசர உதவி",
    help: "உதவி மையம்",
    family: "எனக்கு நம்பிக்கையானவர்கள்",
    myDay: "எனது நாள்",
    scamShield: "பாதுகாப்பு கவசம்",
    accessibility: "அணுகல் அமைப்புகள்",
    whyWeBuilt: "ஏன் உருவாக்கினோம்",
    designPrinciples: "வடிவமைப்பு கொள்கைகள்",
    accessibilityAudit: "அணுகல் தணிக்கை",

    // Header Actions
    textSize: "எழுத்து அளவு",
    contrast: "மாறுபாடு",
    highContrast: "அதிக மாறுபாடு",
    standardContrast: "இயல்பான நிறம்",
    readAloud: "வாசித்து காட்டு",
    emergencyHelp: "🔴 அவசர உதவி",
    imStuck: "🟠 உதவி தேவை (எனக்கு புரியவில்லை)",

    // Homepage
    heroTitle: "தொழில்நுட்பம் கடினமாக இருக்க வேண்டியதில்லை.",
    heroSubtitle: "அன்றாட வாழ்விற்கான எளிய கருவிகள் — உங்களுக்காகவே வடிவமைக்கப்பட்டவை.",
    startHere: "இங்கே தொடங்கவும்",
    readPageAloud: "இந்த பக்கத்தை உரக்கப் படிக்கவும்",
    greeting: "காலை வணக்கம்",
    mainQuestion: "இன்று உங்களுக்கு என்ன உதவி வேண்டும்?",
    tellEasyLife: "உங்களுக்கு தேவையானதை ஈசி லைஃபிடம் சொல்லுங்கள்",
    voicePlaceholder: "மைக்கை தொட்டுப் பேசுங்கள்...",

    // Service Cards
    healthcareTitle: "மருத்துவ சேவை",
    healthcareDesc: "மருத்துவமனைகள், மருத்துவர்கள் மற்றும் முன்பதிவுகளைக் கண்டறியவும்.",
    moneyTitle: "பணம் & வங்கிச் சேவை",
    moneyDesc: "வங்கிச் சேவை, ஓய்வூதியம் மற்றும் நிதிப் பாதுகாப்பைப் புரிந்து கொள்ளுங்கள்.",
    travelTitle: "பயணம்",
    travelDesc: "எளிய போக்குவரத்து மற்றும் வழிகளைக் கண்டறியவும்.",
    govtTitle: "அரசு சேவைகள்",
    govtDesc: "அரசு சேவைகள் மற்றும் விண்ணப்பங்களுக்கு உதவி பெறவும்.",
    emergencyTitle: "அவசரம்",
    emergencyDesc: "விரைவாக அவசர உதவி பெறவும்.",
    familyTitle: "குடும்பத்தாரை தொடர்புகொள்ள",
    familyDesc: "நீங்கள் நம்பும் ஒருவரை அழைக்கவும் அல்லது செய்தி அனுப்பவும்.",

    // Extra Homepage Sections
    whatMakesDifferent: "ஈசி லைஃப் எவ்வாறு வித்தியாசமானது?",
    diff1: "சிக்கலான தகவல்களை எளிமையாக விளக்கும்.",
    diff2: "உங்களுக்கு படிப்படியாக வழிகாட்டும்.",
    diff3: "முக்கிய தகவல்களை உரக்கப் படிக்கும்.",
    diff4: "சந்தேகத்திற்குரிய செய்திகளை அடையாளம் காண உதவும்.",
    diff5: "நம்பிக்கையான நபரிடம் உதவி கேட்க அனுமதிக்கும்.",

    youAreInControl: "அனைத்தும் உங்கள் கட்டுப்பாட்டில்",
    ctrl1: "படிக்க எளிதானது",
    ctrl2: "கேட்க எளிதானது",
    ctrl3: "புரிந்துகொள்ள எளிதானது",
    ctrl4: "உங்கள் மொழியில் கிடைக்கிறது",
    ctrl5: "தொழில்நுட்ப அறிவு தேவையில்லை",

    // Signature Features
    explainThis: "இதை விளக்கு",
    showMe: "காண்பி",
    scamShieldTitle: "இந்த செய்தி பாதுகாப்பானதா?",
    confidenceCheckTitle: "அனைத்தும் முடிந்தது!",

    // Onboarding
    onboardingTitle: "ஈசி லைஃபை உங்களுக்கு வசதியாக மாற்றுவோம்.",
    onboardingSub: "தொழில்நுட்பத்தை எவ்வாறு பயன்படுத்துவது என்பது உங்களுக்குத் தெரிய வேண்டியதில்லை.",
    q1: "தகவல் உங்களுக்கு எப்படி வேண்டும்?",
    q2: "உங்களுக்கு எவ்வளவு உதவி வேண்டும்?",
    q3: "எந்த எழுத்து அளவு வசதியாக உள்ளது?",
    q4: "நீங்கள் விரும்பும் மொழி எது?",
    savePreferences: "அமைப்புகளைச் சேமிக்கவும்",

    // Common Buttons
    goBack: "பின்னே செல்",
    confirm: "உறுதிசெய்",
    cancel: "ரத்து செய்",
    close: "மூடு",
    yes: "ஆம்",
    no: "இல்லை",
    startAgain: "மீண்டும் தொடங்கு",
    call: "அழைக்கவும்",
    message: "செய்தி அனுப்பு"
  },

  Hindi: {
    appName: "EasyLife",
    tagline: "तकनीक सीखें नहीं, तकनीक को अपने अनुसार ढालें।",
    home: "होम",
    healthcare: "स्वास्थ्य सेवा",
    services: "सेवाएं",
    emergency: "आपातकालीन",
    help: "सहायता",
    family: "मेरे भरोसेमंद लोग",
    myDay: "मेरा दिन",
    scamShield: "स्कैम शील्ड",
    accessibility: "पहुंच क्षमता",
    whyWeBuilt: "क्यों बनाया",
    designPrinciples: "डिजाइन सिद्धांत",
    accessibilityAudit: "ऑडिट",
    textSize: "अक्षर का आकार",
    contrast: "कंट्रास्ट",
    highContrast: "उच्च कंट्रास्ट",
    standardContrast: "सामान्य कंट्रास्ट",
    readAloud: "पढ़कर सुनाएं",
    emergencyHelp: "🔴 आपातकालीन सहायता",
    imStuck: "🟠 मैं अटक गया हूँ — मदद करें",
    heroTitle: "तकनीक कठिन होने की ज़रूरत नहीं है।",
    heroSubtitle: "दैनिक जीवन के लिए सरल उपकरण — आपके लिए बनाए गए।",
    startHere: "यहाँ से शुरू करें",
    readPageAloud: "यह पेज पढ़कर सुनाएं",
    greeting: "सुप्रभात",
    mainQuestion: "आज आपको क्या चाहिए?",
    tellEasyLife: "EasyLife को बताएं कि आपको क्या चाहिए",
    voicePlaceholder: "माइक दबाएं और बोलें...",
    healthcareTitle: "स्वास्थ्य सेवा",
    healthcareDesc: "अस्पताल और डॉक्टर खोजें।",
    moneyTitle: "पैसा और बैंकिंग",
    moneyDesc: "बैंकिंग और पेंशन सुरक्षा समझें।",
    travelTitle: "यात्रा",
    travelDesc: "सरल परिवहन और दिशा-निर्देश।",
    govtTitle: "सरकारी सेवाएं",
    govtDesc: "सरकारी योजनाओं में मदद।",
    emergencyTitle: "आपातकालीन",
    emergencyDesc: "तुरंत मदद पाएं।",
    familyTitle: "परिवार से संपर्क करें",
    familyDesc: "भरोसेमंद व्यक्ति को कॉल या मैसेज करें।",
    whatMakesDifferent: "EasyLife क्यों अलग है?",
    diff1: "कठिन जानकारी को सरल भाषा में समझाता है।",
    diff2: "कदम-दर-कदम मार्गदर्शन करता है।",
    diff3: "महत्वपूर्ण जानकारी पढ़कर सुनाता है।",
    diff4: "संदिग्ध संदेशों की पहचान करता है।",
    diff5: "परिवार से मदद लेने की सुविधा देता है।",
    youAreInControl: "नियंत्रण आपके हाथ में है",
    ctrl1: "पढ़ने में आसान",
    ctrl2: "सुनने में आसान",
    ctrl3: "समझने में आसान",
    ctrl4: "आपकी भाषा में उपलब्ध",
    ctrl5: "तकनीकी ज्ञान आवश्यक नहीं",
    explainThis: "यह समझाएं",
    showMe: "दिखाएं",
    scamShieldTitle: "क्या यह मैसेज सुरक्षित है?",
    confidenceCheckTitle: "काम पूरा हो गया!",
    onboardingTitle: "EasyLife को आपके लिए आरामदायक बनाते हैं।",
    onboardingSub: "तकनीक का ज्ञान आवश्यक नहीं है।",
    q1: "जानकारी कैसे चाहते हैं?",
    q2: "कितनी सहायता चाहिए?",
    q3: "अक्षर का आकार कौन सा पसंद है?",
    q4: "कौन सी भाषा चुनेंगे?",
    savePreferences: "सेटिंग्स सुरक्षित करें",
    goBack: "वापस जाएं",
    confirm: "पुष्टि करें",
    cancel: "रद्द करें",
    close: "बंद करें",
    yes: "हाँ",
    no: "नहीं",
    startAgain: "पुनः प्रारंभ करें",
    call: "कॉल करें",
    message: "मैसेज करें"
  },

  Malayalam: {
    appName: "EasyLife",
    tagline: "സാങ്കേതികവിദ്യ പഠിക്കേണ്ടതില്ല, സാങ്കേതികവിദ്യ നിങ്ങളിലേക്ക് മാറുന്നു.",
    home: "ഹോം",
    healthcare: "ആരോഗ്യം",
    services: "സേവനങ്ങൾ",
    emergency: "അടിയന്തിരം",
    help: "സഹായം",
    family: "വിശ്വസ്തർ",
    myDay: "എന്റെ ദിവസം",
    scamShield: "സ്കാം ഷീൽഡ്",
    accessibility: "ആക്സസിബിലിറ്റി",
    whyWeBuilt: "ഞങ്ങളുടെ ലക്ഷ്യം",
    designPrinciples: "തത്വങ്ങൾ",
    accessibilityAudit: "ഓഡിറ്റ്",
    textSize: "അക്ഷര വലിപ്പം",
    contrast: "കോൺട്രാസ്റ്റ്",
    highContrast: "ഉയർന്ന കോൺട്രാസ്റ്റ്",
    standardContrast: "സാധാരണ കോൺട്രാസ്റ്റ്",
    readAloud: "വായിച്ചു കേൾപ്പിക്കുക",
    emergencyHelp: "🔴 അടിയന്തിര സഹായം",
    imStuck: "🟠 എനിക്ക് മനസ്സിലാകുന്നില്ല",
    heroTitle: "സാങ്കേതികവിദ്യ പ്രയാസമുള്ളതാകേണ്ടതില്ല.",
    heroSubtitle: "നിങ്ങൾക്കായി രൂപകൽപ്പന ചെയ്ത ലളിതമായ ഉപകരണങ്ങൾ.",
    startHere: "ഇവിടെ തുടങ്ങാം",
    readPageAloud: "ഈ പേജ് വായിക്കുക",
    greeting: "സുപ്രഭാതം",
    mainQuestion: "ഇന്ന് നിങ്ങൾക്ക് എന്താണ് വേണ്ടത്?",
    tellEasyLife: "നിങ്ങളുടെ ആവശ്യം പറയൂ",
    voicePlaceholder: "മൈക്ക് അമർത്തി സംസാരിക്കൂ...",
    healthcareTitle: "ആരോഗ്യം",
    healthcareDesc: "ആശുപത്രികളും ഡോക്ടർമാരെയും കണ്ടെത്തുക.",
    moneyTitle: "ബാങ്കിംഗ്",
    moneyDesc: "പെൻഷൻ, ബാങ്കിംഗ് വിവരങ്ങൾ.",
    travelTitle: "യാത്ര",
    travelDesc: "യാത്രാ വിവരങ്ങൾ.",
    govtTitle: "സർക്കാർ സേവനങ്ങൾ",
    govtDesc: "സർക്കാർ പദ്ധതികൾ.",
    emergencyTitle: "അടിയന്തിരം",
    emergencyDesc: "പെട്ടെന്നുള്ള സഹായം.",
    familyTitle: "കുടുംബം",
    familyDesc: "കുടുംബാംഗങ്ങളെ വിളിക്കുക.",
    whatMakesDifferent: "EasyLife എന്ത് കൊണ്ട് വ്യത്യസ്തമാണ്?",
    diff1: "സങ്കീർണ്ണമായ വിവരങ്ങൾ ലളിതമായി വിവരിക്കുന്നു.",
    diff2: "ഘട്ടം ഘട്ടമായി വഴികാട്ടുന്നു.",
    diff3: "വിവരങ്ങൾ വായിച്ചു കേൾപ്പിക്കുന്നു.",
    diff4: "വ്യാജ സന്ദേശങ്ങൾ തിരിച്ചറിയുന്നു.",
    diff5: "കുടുംബാംഗങ്ങളുടെ സഹായം ഉറപ്പാക്കുന്നു.",
    youAreInControl: "നിയന്ത്രണം നിങ്ങളിൽ ഭദ്രം",
    ctrl1: "വായിക്കാൻ എളുപ്പം",
    ctrl2: "കേൾക്കാൻ എളുപ്പം",
    ctrl3: "മനസ്സിലാക്കാൻ എളുപ്പം",
    ctrl4: "നിങ്ങളുടെ ഭാഷയിൽ",
    ctrl5: "സാങ്കേതിക പരിജ്ഞാനം ആവശ്യമില്ല",
    explainThis: "വിശദീകരിക്കുക",
    showMe: "കാണിച്ചു തരിക",
    scamShieldTitle: "ഈ സന്ദേശം സുരക്ഷിതമാണോ?",
    confidenceCheckTitle: "പൂർത്തിയായി!",
    onboardingTitle: "EasyLife നിങ്ങള്‍ക്ക് അനുയോജ്യമാക്കാം.",
    onboardingSub: "സാങ്കേതികവിദ്യ അറിയേണ്ടതില്ല.",
    q1: "വിവരങ്ങൾ എങ്ങനെ വേണം?",
    q2: "എത്രത്തോളം സഹായം വേണം?",
    q3: "അക്ഷര വലിപ്പം ഏതാണ് സൗകര്യം?",
    q4: "ഏത് ഭാഷ വേണം?",
    savePreferences: "സേവ് ചെയ്യുക",
    goBack: "തിരികെ പോവുക",
    confirm: "ഉറപ്പാക്കുക",
    cancel: "റദ്ദാക്കുക",
    close: "അടയ്ക്കുക",
    yes: "അതെ",
    no: "അല്ല",
    startAgain: "വീണ്ടും തുടങ്ങുക",
    call: "വിളിക്കുക",
    message: "സന്ദേശം അയക്കുക"
  },

  Telugu: {
    appName: "EasyLife",
    tagline: "సాంకేతికతను నేర్చుకోవద్దు, సాంకేతికతే ನಿಮ್ಮ ప్రకారం మారుతుంది.",
    home: "హోమ్",
    healthcare: "వైద్య సేవలు",
    services: "సేవలు",
    emergency: "అత్యవసరం",
    help: "సహాయం",
    family: "నమ్మకమైన వారు",
    myDay: "నా రోజు",
    scamShield: "స్కామ్ షీల్డ్",
    accessibility: "అనుకూలత",
    whyWeBuilt: "ఎందుకు నిర్మించాం",
    designPrinciples: "సూత్రాలు",
    accessibilityAudit: "ఆడిట్",
    textSize: "అక్షర పరిమాణం",
    contrast: "కాంట్రాస్ట్",
    highContrast: "హై కాంట్రాస్ట్",
    standardContrast: "సాధారణ కాంట్రాస్ట్",
    readAloud: "చదివి వినిపించు",
    emergencyHelp: "🔴 అత్యవసర సహాయం",
    imStuck: "🟠 నాకు సహాయం కావాలి",
    heroTitle: "సాంకేతికత కష్టంగా ఉండాల్సిన అవసరం లేదు.",
    heroSubtitle: "మీ కోసమే ప్రత్యేకంగా రూపొందించబడిన సరళమైన సాధనాలు.",
    startHere: "ఇక్కడ ప్రారంభించండి",
    readPageAloud: "ఈ పేజీని చదవండి",
    greeting: "శుభోదయం",
    mainQuestion: "ఈ రోజు మీకు ఏమి కావాలి?",
    tellEasyLife: "EasyLife కి మీ అవసరం చెప్పండి",
    voicePlaceholder: "మైక్ నొక్కి మాట్లాడండి...",
    healthcareTitle: "వైద్య సేవలు",
    healthcareDesc: "ఆసుపత్రులు మరియు డాక్టర్లను కనుగొనండి.",
    moneyTitle: "బ్యాంకింగ్ సేవలు",
    moneyDesc: "బ్యాంకింగ్ మరియు పెన్షన్ భద్రత.",
    travelTitle: "ప్రయాణం",
    travelDesc: "రవాణా సమాచారం.",
    govtTitle: "ప్రభుత్వ సేవలు",
    govtDesc: "ప్రభుత్వ పథకాల సేవలు.",
    emergencyTitle: "అత్యవసరం",
    emergencyDesc: "వెంటనే సహాయం పొందండి.",
    familyTitle: "కుటుంబ సభ్యులకు ఫోన్ చేయండి",
    familyDesc: "నమ్మకమైన వారికి కాల్ లేదా మెసేజ్ చేయండి.",
    whatMakesDifferent: "EasyLife ప్రత్యేకం ఏమిటి?",
    diff1: "క్లిష్టమైన సమాచారాన్ని సులభంగా వివరిస్తుంది.",
    diff2: "దశలవారీగా మార్గదర్శనం చేస్తుంది.",
    diff3: "ముఖ్యమైన సమాచారాన్ని చదివి వినిపిస్తుంది.",
    diff4: "అనుమానాస్పద మెసేజ్‌లను గుర్తిస్తుంది.",
    diff5: "కుటుంబ సభ్యుల సహాయం కోరే సదుపాయం.",
    youAreInControl: "మీ నియంత్రణలోనే ఉంటుంది",
    ctrl1: "చదవడానికి సులభం",
    ctrl2: "వినడానికి సులభం",
    ctrl3: "అర్థం చేసుకోవడానికి సులభం",
    ctrl4: "మీ భాషలో లభిస్తుంది",
    ctrl5: "సాంకేతిక పరిజ్ఞానం అవసరం లేదు",
    explainThis: "వివరించు",
    showMe: "చూపించు",
    scamShieldTitle: "ఈ మెసేజ్ సురక్షితమేనా?",
    confidenceCheckTitle: "పూర్తయింది!",
    onboardingTitle: "EasyLife ని మీకు అనుకూలంగా మార్చుకుందాం.",
    onboardingSub: "సాంకేతిక పరిజ్ఞానం అవసరం లేదు.",
    q1: "సమాచారం ఎలా కావాలి?",
    q2: "ఎంత సహాయం కావాలి?",
    q3: "అక్షర పరిమాణం ఏది బాగుంది?",
    q4: "ఏ భాష కావాలి?",
    savePreferences: "సేవ్ చేయండి",
    goBack: "వెనుకకు వెళ్లు",
    confirm: "సరే",
    cancel: "రద్దు చేయి",
    close: "మూసివేయి",
    yes: "అవును",
    no: "కాదు",
    startAgain: "మళ్ళీ ప్రారంభించు",
    call: "కాల్ చేయండి",
    message: "మెసేజ్ చేయండి"
  }
};

interface LanguageContextType {
  language: Language;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ language: Language; children: ReactNode }> = ({
  language,
  children,
}) => {
  const t = (key: string): string => {
    const dict = translations[language] || translations.English;
    return dict[key] || translations.English[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
