import React, { createContext, useContext, ReactNode } from 'react';
import { Language } from '../types';

export const translations: Record<Language, Record<string, string>> = {
  English: {
    // Header & Brand
    appName: "EasyLife",
    tagline: "Technology made easier.",
    adaptiveActive: "Adaptive Accessibility Active",
    customizeSetup: "Customize Setup",
    techMadeEasier: "Technology made easier.",

    // Navigation
    home: "Home",
    healthcare: "Healthcare",
    services: "Services",
    myDay: "My Day",
    help: "Help",
    promptLab: "Prompt Lab",
    problem: "The Problem",
    research: "Research",
    guidedDemo: "Guided Demo",
    emergency: "Emergency",
    accessibility: "Accessibility",

    // Hero Section
    designedForSeniors: "DESIGNED FOR 60+ ADULTS",
    heroTitlePart1: "Technology ",
    heroTitleHighlight: "doesn't have to be difficult.",
    heroSubtitle: "Simple tools for everyday life — designed to be easy to read, easy to understand, and easy to use.",
    startHere: "Start Here →",
    readPageAloud: "🔊 Read This Page Aloud",
    noTechRequired: "No technical knowledge required.",

    // Adaptive Experience Card
    adaptiveReadyTitle: "Your EasyLife is ready for you",
    adaptiveReadySub: "We've made the experience comfortable for you.",
    customizeExperience: "Customize My Experience",
    largeTextChip: "✓ Large Text",
    languageChip: "✓ Language Selected",
    readAloudChip: "✓ Read Aloud Active",
    simpleModeChip: "✓ Simple Mode Active",

    // Voice Interaction Section
    tellEasyLife: "Tell EasyLife what you need",
    speakNaturally: "You can speak naturally or choose an option.",
    talkToEasyLife: "🎙️ Talk to EasyLife",
    listeningNow: "Listening now...",

    // Service Cards Section
    whatDoYouNeedToday: "What do you need today?",
    chooseOneGuide: "Choose one. We'll guide you step by step.",
    
    healthcareTitle: "Healthcare",
    healthcareDesc: "Find hospitals, doctors and appointments.",
    moneyTitle: "Money & Banking",
    moneyDesc: "Understand money and stay safer from scams.",
    travelTitle: "Travel",
    travelDesc: "Find buses, trains and simple directions.",
    govtTitle: "Government Services",
    govtDesc: "Get help with government services and applications.",
    emergencyTitle: "Emergency",
    emergencyDesc: "Get urgent help quickly.",
    familyTitle: "Contact Family",
    familyDesc: "Call or message someone you trust.",

    // Signature Features Section
    signatureHelpTitle: "EasyLife helps you understand what to do next.",
    explainThisTitle: "1. Explain This",
    explainThisDesc: "Turn complicated digital language into simple words.",
    showMeTitle: "2. Show Me",
    showMeDesc: "Follow one clear step at a time.",
    scamShieldTitle: "3. Scam Shield",
    scamShieldDesc: "Understand warning signs in suspicious messages.",
    imStuckTitle: "4. I'm Stuck",
    imStuckDesc: "Get help when you don't know what to do next.",

    // Bottom Action Bar
    emergencyBtn: "EMERGENCY",
    imStuckBtn: "🟠 I'm Stuck — Help Me",
    readAloudBtn: "🔊 Read Aloud",
    easyTalkBtn: "EasyTalk",

    // Common Buttons & Labels
    open: "Open",
    goBack: "Go Back",
    confirm: "Confirm",
    cancel: "Cancel",
    close: "Close",
    yes: "Yes",
    no: "No",
    startAgain: "Start Again",
    call: "Call",
    message: "Message",
    view: "View",
    done: "Done",
    remindMe: "Remind Me",
    checkMessage: "Check Message",
    beCareful: "⚠️ Be careful",
  },

  Tamil: {
    // Header & Brand
    appName: "ஈசி லைஃப் (EasyLife)",
    tagline: "தொழில்நுட்பம் எளிதானது.",
    adaptiveActive: "அணுகல் அமைப்புகள் இயங்குகிறது",
    customizeSetup: "அமைப்புகளை மாற்றுக",
    techMadeEasier: "தொழில்நுட்பம் எளிதானது.",

    // Navigation
    home: "முகப்பு",
    healthcare: "மருத்துவ சேவை",
    services: "சேவைகள்",
    myDay: "எனது நாள்",
    help: "உதவி மையம்",
    promptLab: "ப்ராம்ப்ட் லேப்",
    problem: "சிக்கல்கள்",
    research: "ஆராய்ச்சி",
    guidedDemo: "வழிகாட்டி டெமோ",
    emergency: "அவசரம்",
    accessibility: "அணுகல்",

    // Hero Section
    designedForSeniors: "60+ வயதினருக்கான வடிவமைப்பு",
    heroTitlePart1: "தொழில்நுட்பம் ",
    heroTitleHighlight: "கடினமாக இருக்க வேண்டியதில்லை.",
    heroSubtitle: "அன்றாட வாழ்விற்கான எளிய கருவிகள் — படிக்க, புரிந்துகொள்ள மற்றும் பயன்படுத்த எளிதானவை.",
    startHere: "இங்கே தொடங்கவும் →",
    readPageAloud: "🔊 உரக்கப் படிக்கவும்",
    noTechRequired: "தொழில்நுட்ப அறிவு தேவையில்லை.",

    // Adaptive Experience Card
    adaptiveReadyTitle: "உங்கள் ஈசி லைஃப் தயார்",
    adaptiveReadySub: "உங்களுக்கு வசதியான அனுபவத்தை உருவாக்கியுள்ளோம்.",
    customizeExperience: "அமைப்புகளை மாற்று",
    largeTextChip: "✓ பெரிய எழுத்துக்கள்",
    languageChip: "✓ தமிழ் மொழி",
    readAloudChip: "✓ வாசித்து காட்டும் வசதி",
    simpleModeChip: "✓ எளிய முறை",

    // Voice Interaction Section
    tellEasyLife: "தேவையானதை ஈசி லைஃபிடம் சொல்லுங்கள்",
    speakNaturally: "நீங்கள் பேசலாம் அல்லது ஒரு தேர்வை தேர்ந்தெடுக்கலாம்.",
    talkToEasyLife: "🎙️ பேசுங்கள்",
    listeningNow: "கேட்கிறது...",

    // Service Cards Section
    whatDoYouNeedToday: "இன்று உங்களுக்கு என்ன தேவை?",
    chooseOneGuide: "ஒன்றைத் தேர்ந்தெடுக்கவும். நாங்கள் வழிகாட்டுவோம்.",

    healthcareTitle: "மருத்துவ சேவை",
    healthcareDesc: "மருத்துவமனைகள், மருத்துவர்கள் மற்றும் முன்பதிவுகள்.",
    moneyTitle: "பணம் & வங்கி",
    moneyDesc: "வங்கிச் சேவை மற்றும் மோசடி பாதுகாப்பு.",
    travelTitle: "பயணம்",
    travelDesc: "பேருந்து, ரயில் மற்றும் எளிய வழிகள்.",
    govtTitle: "அரசு சேவைகள்",
    govtDesc: "அரசு சேவைகள் மற்றும் விண்ணப்ப உதவி.",
    emergencyTitle: "அவசர உதவி",
    emergencyDesc: "விரைவாக அவசர உதவி பெறவும்.",
    familyTitle: "குடும்ப தொடர்பு",
    familyDesc: "நம்பிக்கையான நபரை அழைக்கவும் அல்லது செய்தி அனுப்பவும்.",

    // Signature Features Section
    signatureHelpTitle: "அடுத்து என்ன செய்ய வேண்டும் என்பதை ஈசி லைஃப் விளக்கும்.",
    explainThisTitle: "1. இதை விளக்கு",
    explainThisDesc: "சிக்கலான சொற்களை எளிய வார்த்தைகளாக மாற்றும்.",
    showMeTitle: "2. காண்பி",
    showMeDesc: "படிப்படியாக வழிகாட்டும்.",
    scamShieldTitle: "3. பாதுகாப்பு கவசம்",
    scamShieldDesc: "சந்தேகத்திற்குரிய செய்திகளின் அபாயங்களை அறியலாம்.",
    imStuckTitle: "4. எனக்கு புரியவில்லை",
    imStuckDesc: "என்ன செய்வதென்று தெரியாதபோது உதவி பெறலாம்.",

    // Bottom Action Bar
    emergencyBtn: "அவசரம்",
    imStuckBtn: "🟠 எனக்கு புரியவில்லை — உதவி செய்",
    readAloudBtn: "🔊 வாசித்து காட்டு",
    easyTalkBtn: "பேசுங்கள்",

    // Common Buttons & Labels
    open: "திறக்கவும்",
    goBack: "பின்னே செல்",
    confirm: "உறுதிசெய்",
    cancel: "ரத்து செய்",
    close: "மூடு",
    yes: "ஆம்",
    no: "இல்லை",
    startAgain: "மீண்டும் தொடங்கு",
    call: "அழைக்கவும்",
    message: "செய்தி அனுப்பு",
    view: "பார்க்க",
    done: "முடிந்தது",
    remindMe: "நினைவுபடுத்து",
    checkMessage: "செய்தியை பரிசோதி",
    beCareful: "⚠️ எச்சரிக்கை",
  },

  Hindi: {
    appName: "EasyLife",
    tagline: "तकनीक आसान बनाई गई।",
    adaptiveActive: "सुगम पहुँच सक्रिय",
    customizeSetup: "सेटिंग्स बदलें",
    techMadeEasier: "तकनीक आसान बनाई गई।",
    home: "होम",
    healthcare: "स्वास्थ्य सेवा",
    services: "सेवाएं",
    myDay: "मेरा दिन",
    help: "सहायता",
    promptLab: "प्रॉम्प्ट लैब",
    problem: "समस्याएं",
    research: "अनुसंधान",
    guidedDemo: "गाइडेड डेमो",
    emergency: "आपातकालीन",
    accessibility: "सुगम पहुँच",
    designedForSeniors: "60+ वरिष्ठों के लिए",
    heroTitlePart1: "तकनीक ",
    heroTitleHighlight: "कठिन होने की आवश्यकता नहीं है।",
    heroSubtitle: "दैनिक जीवन के लिए सरल उपकरण — पढ़ने, समझने और उपयोग करने में आसान।",
    startHere: "यहाँ से शुरू करें →",
    readPageAloud: "🔊 बोलकर सुनाएं",
    noTechRequired: "तकनीकी ज्ञान आवश्यक नहीं।",
    adaptiveReadyTitle: "आपकी EasyLife तैयार है",
    adaptiveReadySub: "हमने आपके लिए अनुभव को आरामदायक बनाया है।",
    customizeExperience: "सेटिंग्स बदलें",
    largeTextChip: "✓ बड़े अक्षर",
    languageChip: "✓ हिंदी भाषा",
    readAloudChip: "✓ वॉइस चालू",
    simpleModeChip: "✓ सरल मोड",
    tellEasyLife: "EasyLife को अपनी आवश्यकता बताएं",
    speakNaturally: "आप बोल सकते हैं या विकल्प चुन सकते हैं।",
    talkToEasyLife: "🎙️ EasyLife से बोलें",
    listeningNow: "सुन रहा है...",
    whatDoYouNeedToday: "आज आपको क्या चाहिए?",
    chooseOneGuide: "एक चुनें। हम मार्गदर्शन करेंगे।",
    healthcareTitle: "स्वास्थ्य सेवा",
    healthcareDesc: "अस्पताल, डॉक्टर और अपॉइंटमेंट खोजें।",
    moneyTitle: "पैसा और बैंकिंग",
    moneyDesc: "बैंकिंग समझें और धोखाधड़ी से बचें।",
    travelTitle: "यात्रा",
    travelDesc: "बस, ट्रेन और आसान रास्ते खोजें।",
    govtTitle: "सरकारी सेवाएं",
    govtDesc: "सरकारी सेवाओं में मदद लें।",
    emergencyTitle: "आपातकालीन",
    emergencyDesc: "तुरंत मदद पाएं।",
    familyTitle: "परिवार से संपर्क करें",
    familyDesc: "भरोसेमंद व्यक्ति को कॉल या मैसेज करें।",
    signatureHelpTitle: "EasyLife आपको बताती है कि आगे क्या करना है।",
    explainThisTitle: "1. यह समझाएं",
    explainThisDesc: "कठिन शब्दों को सरल भाषा में बदलें।",
    showMeTitle: "2. दिखाएं",
    showMeDesc: "कदम-दर-कदम मार्गदर्शन।",
    scamShieldTitle: "3. स्कैम शील्ड",
    scamShieldDesc: "संदेहजनक संदेशों के खतरे समझें।",
    imStuckTitle: "4. मैं अटक गया हूँ",
    imStuckDesc: "मदद पाएं जब समझ न आए।",
    emergencyBtn: "आपातकालीन",
    imStuckBtn: "🟠 मैं अटक गया हूँ — मदद करें",
    readAloudBtn: "🔊 बोलकर सुनाएं",
    easyTalkBtn: "बोलें",
    open: "खोले",
    goBack: "वापस जाएं",
    confirm: "पुष्टि करें",
    cancel: "रद्द करें",
    close: "बंद करें",
    yes: "हाँ",
    no: "नहीं",
    startAgain: "पुनः प्रारंभ करें",
    call: "कॉल करें",
    message: "मैसेज करें",
    view: "देखें",
    done: "हो गया",
    remindMe: "याद दिलाएं",
    checkMessage: "संदेश जांचें",
    beCareful: "⚠️ सावधान रहें",
  },

  Malayalam: {
    appName: "EasyLife",
    tagline: "സാങ്കേതികവിദ്യ എളുപ്പമാക്കി.",
    adaptiveActive: "സഹായ സംവിധാനം സജീവം",
    customizeSetup: "മാറ്റങ്ങൾ വരുത്തുക",
    techMadeEasier: "സാങ്കേതികവിദ്യ എളുപ്പമാക്കി.",
    home: "ഹോം",
    healthcare: "ആരോഗ്യം",
    services: "സേവനങ്ങൾ",
    myDay: "എന്റെ ദിവസം",
    help: "സഹായം",
    promptLab: "പ്രോംപ്റ്റ് ലാബ്",
    problem: "പ്രശ്നങ്ങൾ",
    research: "ഗവേഷണം",
    guidedDemo: "ഡെമോ",
    emergency: "അടിയന്തിരം",
    accessibility: "ആക്സസിബിലിറ്റി",
    designedForSeniors: "60+ മുതിർന്നവർക്കായി",
    heroTitlePart1: "സാങ്കേതികവിദ്യ ",
    heroTitleHighlight: "കഠിനമാകേണ്ടതില്ല.",
    heroSubtitle: "ദൈനംദിന ജീവിതത്തിനായുള്ള ലളിതമായ ഉപകരണങ്ങൾ.",
    startHere: "ഇവിടെ തുടങ്ങാം →",
    readPageAloud: "🔊 വായിച്ചു കേൾക്കുക",
    noTechRequired: "സാങ്കേതിക പരിജ്ഞാനം ആവശ്യമില്ല.",
    adaptiveReadyTitle: "EasyLife തയ്യാറാണ്",
    adaptiveReadySub: "നിങ്ങൾക്കായി എളുപ്പമുള്ള അനുഭവം.",
    customizeExperience: "മാറ്റങ്ങൾ വരുത്തുക",
    largeTextChip: "✓ വലിയ അക്ഷരങ്ങൾ",
    languageChip: "✓ മലയാളം",
    readAloudChip: "✓ വോയിസ് സജീവം",
    simpleModeChip: "✓ ലളിത മോഡ്",
    tellEasyLife: "ആവശ്യം പറയൂ",
    speakNaturally: "നിങ്ങൾക്ക് സംസാരിക്കാം.",
    talkToEasyLife: "🎙️ സംസാരിക്കൂ",
    listeningNow: "കേൾക്കുന്നു...",
    whatDoYouNeedToday: "ഇന്ന് എന്താണ് വേണ്ടത്?",
    chooseOneGuide: "ഒന്ന് തിരഞ്ഞെടുക്കൂ.",
    healthcareTitle: "ആരോഗ്യം",
    healthcareDesc: "ആശുപത്രികളും ഡോക്ടർമാരെയും കണ്ടെത്തുക.",
    moneyTitle: "ബാങ്കിംഗ്",
    moneyDesc: "പണ ഇടപാടുകളും സുരക്ഷയും.",
    travelTitle: "യാത്ര",
    travelDesc: "ബസ്, ട്രെയിൻ വിവരങ്ങൾ.",
    govtTitle: "സർക്കാർ സേവനങ്ങൾ",
    govtDesc: "സർക്കാർ പദ്ധതികൾ.",
    emergencyTitle: "അടിയന്തിരം",
    emergencyDesc: "പെട്ടെന്നുള്ള സഹായം.",
    familyTitle: "കുടുംബം",
    familyDesc: "കുടുംബാംഗങ്ങളെ വിളിക്കുക.",
    signatureHelpTitle: "അടുത്ത നടപടി EasyLife കാട്ടിത്തരും.",
    explainThisTitle: "1. വിവരിക്കൂ",
    explainThisDesc: "സങ്കീർണ്ണ പദങ്ങൾ ലളിതമാക്കൂ.",
    showMeTitle: "2. കാണിച്ച് തരിക",
    showMeDesc: "ഘട്ടം ഘട്ടമായുള്ള ഗൈഡ്.",
    scamShieldTitle: "3. സ്കാം ഷീൽഡ്",
    scamShieldDesc: "വ്യാജ സന്ദേശങ്ങൾ തിരിച്ചറിയൂ.",
    imStuckTitle: "4. മനസ്സിലാകുന്നില്ല",
    imStuckDesc: "ഉടൻ സഹായം നേടൂ.",
    emergencyBtn: "അടിയന്തിരം",
    imStuckBtn: "🟠 എനിക്ക് മനസ്സിലാകുന്നില്ല — സഹായിക്കൂ",
    readAloudBtn: "🔊 വായിക്കുക",
    easyTalkBtn: "സംസാരിക്കൂ",
    open: "തുറക്കുക",
    goBack: "തിരികെ പോവുക",
    confirm: "ഉറപ്പാക്കുക",
    cancel: "റദ്ദാക്കുക",
    close: "അടയ്ക്കുക",
    yes: "അതെ",
    no: "അല്ല",
    startAgain: "വീണ്ടും തുടങ്ങുക",
    call: "വിളിക്കുക",
    message: "സന്ദേശം അയക്കുക",
    view: "കാണുക",
    done: "പൂർത്തിയായി",
    remindMe: "ഓർമ്മിപ്പിക്കുക",
    checkMessage: "സന്ദേശം പരിശോധിക്കുക",
    beCareful: "⚠️ ശ്രദ്ധിക്കുക",
  },

  Telugu: {
    appName: "EasyLife",
    tagline: "సాంకేతికత సులభతరం చేయబడింది.",
    adaptiveActive: "అనుకూల సేవలు క్రియాశీలంగా ఉన్నాయి",
    customizeSetup: "సెట్టింగ్‌లు మార్చండి",
    techMadeEasier: "సాంకేతికత సులభతరం చేయబడింది.",
    home: "హోమ్",
    healthcare: "వైద్య సేవలు",
    services: "సేవలు",
    myDay: "నా రోజు",
    help: "సహాయం",
    promptLab: "ప్రాంప్ట్ ల్యాబ్",
    problem: "సమస్యలు",
    research: "పరిశోధన",
    guidedDemo: "డెమో",
    emergency: "అత్యవసరం",
    accessibility: "అనుకూలత",
    designedForSeniors: "60+ వయోవృద్ధుల కోసం",
    heroTitlePart1: "సాంకేతికత ",
    heroTitleHighlight: "కష్టంగా ఉండాల్సిన అవసరం లేదు.",
    heroSubtitle: "రోజువారీ జీవితం కోసం సరళమైన సాధనాలు.",
    startHere: "ఇక్కడ ప్రారంభించండి →",
    readPageAloud: "🔊 చదివి వినిపించు",
    noTechRequired: "సాంకేతిక పరిజ్ఞానం అవసరం లేదు.",
    adaptiveReadyTitle: "మీ EasyLife సిద్ధంగా ఉంది",
    adaptiveReadySub: "మీ కోసం సులభమైన అనుభవం.",
    customizeExperience: "సెట్టింగ్‌లు మార్చండి",
    largeTextChip: "✓ పెద్ద అక్షరాలు",
    languageChip: "✓ తెలుగు భాష",
    readAloudChip: "✓ వాయిస్ ప్రారంభమైంది",
    simpleModeChip: "✓ సరళ మోడ్",
    tellEasyLife: "మీ అవసరం చెప్పండి",
    speakNaturally: "మీరు మాట్లాడవచ్చు.",
    talkToEasyLife: "🎙️ మాట్లాడండి",
    listeningNow: "వింటోంది...",
    whatDoYouNeedToday: "ఈ రోజు మీకు ఏమి కావాలి?",
    chooseOneGuide: "ఒకటి ఎంచుకోండి.",
    healthcareTitle: "వైద్య సేవలు",
    healthcareDesc: "ఆసుపత్రులు మరియు డాక్టర్లను కనుగొనండి.",
    moneyTitle: "బ్యాంకింగ్",
    moneyDesc: "పని మరియు భద్రత.",
    travelTitle: "ప్రయాణం",
    travelDesc: "బస్సు మరియు రైలు వివరాలు.",
    govtTitle: "ప్రభుత్వ సేవలు",
    govtDesc: "ప్రభుత్వ పథకాల సహాయం.",
    emergencyTitle: "అత్యవసరం",
    emergencyDesc: "వెంటనే సహాయం పొందండి.",
    familyTitle: "కుటుంబం",
    familyDesc: "నమ్మకమైన వారికి ఫోన్ చేయండి.",
    signatureHelpTitle: "తరువాత ఏమి చేయాలో EasyLife చూపిస్తుంది.",
    explainThisTitle: "1. వివరించు",
    explainThisDesc: "క్లిష్ట పదాలను సులభం చేయండి.",
    showMeTitle: "2. చూపించు",
    showMeDesc: "దశలవారీ మార్గదర్శనం.",
    scamShieldTitle: "3. స్కామ్ షీల్డ్",
    scamShieldDesc: "నకిలీ సందేశాలను గుర్తించండి.",
    imStuckTitle: "4. నాకు అర్థం కాలేదు",
    imStuckDesc: "వెంటనే సహాయం పొందండి.",
    emergencyBtn: "అత్యవసరం",
    imStuckBtn: "🟠 నాకు అర్థం కాలేదు — సహాయం చేయి",
    readAloudBtn: "🔊 చదివి వినిపించు",
    easyTalkBtn: "మాట్లాడండి",
    open: "తెరవండి",
    goBack: "వెనుకకు వెళ్లు",
    confirm: "సరే",
    cancel: "రద్దు చేయి",
    close: "మూసివేయి",
    yes: "అవును",
    no: "కాదు",
    startAgain: "మళ్ళీ ప్రారంభించు",
    call: "కాల్ చేయండి",
    message: "మెసేజ్ చేయండి",
    view: "చూడండి",
    done: "పూర్తయింది",
    remindMe: "గుర్తు చేయి",
    checkMessage: "సందేశం తనిఖీ చేయి",
    beCareful: "⚠️ జాగ్రత్త",
  }
};

interface LanguageContextType {
  language: Language;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ language: Language; children: ReactNode }> = ({
  language,
  children,
}) => {
  const t = (key: string): string => {
    const dict = translations[language] || translations.English;
    return dict[key] || translations.English[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
